services:
  - type: web
    name: haifa-rag
    runtime: docker
    plan: starter
    envVars:
      - key: LLM_API_KEY
        sync: false
      - key: LLM_BASE_URL
        sync: false
      - key: LLM_MODEL
        sync: false
      - key: EMBEDDING_MODEL
        sync: false
      - key: GEMINI_EMBEDDING_API_KEY
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_SQL_PATH
        sync: false
